window.esdocSearchIndex = [
  [
    "@meese-os/server/src/providers/auth.js~authserviceprovider",
    "class/src/providers/auth.js~AuthServiceProvider.html",
    "<span>AuthServiceProvider</span> <span class=\"search-result-import-path\">@meese-os/server/src/providers/auth.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/core.js~core",
    "class/src/core.js~Core.html",
    "<span>Core</span> <span class=\"search-result-import-path\">@meese-os/server/src/core.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/core.js~corebase",
    "variable/index.html#static-variable-CoreBase",
    "<span>CoreBase</span> <span class=\"search-result-import-path\">@meese-os/server/src/core.js</span>",
    "variable"
  ],
  [
    "@meese-os/server/src/providers/core.js~coreserviceprovider",
    "class/src/providers/core.js~CoreServiceProvider.html",
    "<span>CoreServiceProvider</span> <span class=\"search-result-import-path\">@meese-os/server/src/providers/core.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/filesystem.js~filesystem",
    "class/src/filesystem.js~Filesystem.html",
    "<span>Filesystem</span> <span class=\"search-result-import-path\">@meese-os/server/src/filesystem.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/package.js~package",
    "class/src/package.js~Package.html",
    "<span>Package</span> <span class=\"search-result-import-path\">@meese-os/server/src/package.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/providers/packages.js~packageserviceprovider",
    "class/src/providers/packages.js~PackageServiceProvider.html",
    "<span>PackageServiceProvider</span> <span class=\"search-result-import-path\">@meese-os/server/src/providers/packages.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/packages.js~packages",
    "class/src/packages.js~Packages.html",
    "<span>Packages</span> <span class=\"search-result-import-path\">@meese-os/server/src/packages.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/providers/auth.js~serviceprovider",
    "variable/index.html#static-variable-ServiceProvider",
    "<span>ServiceProvider</span> <span class=\"search-result-import-path\">@meese-os/server/src/providers/auth.js</span>",
    "variable"
  ],
  [
    "@meese-os/server/src/settings.js~settings",
    "class/src/settings.js~Settings.html",
    "<span>Settings</span> <span class=\"search-result-import-path\">@meese-os/server/src/settings.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/providers/settings.js~settingsserviceprovider",
    "class/src/providers/settings.js~SettingsServiceProvider.html",
    "<span>SettingsServiceProvider</span> <span class=\"search-result-import-path\">@meese-os/server/src/providers/settings.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/utils/token-factory.js~tokenfactory",
    "class/src/utils/token-factory.js~TokenFactory.html",
    "<span>TokenFactory</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/token-factory.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/providers/token-factory.js~tokenfactoryserviceprovider",
    "class/src/providers/token-factory.js~TokenFactoryServiceProvider.html",
    "<span>TokenFactoryServiceProvider</span> <span class=\"search-result-import-path\">@meese-os/server/src/providers/token-factory.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/utils/token-storage.js~tokenstorage",
    "class/src/utils/token-storage.js~TokenStorage.html",
    "<span>TokenStorage</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/token-storage.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/providers/token-storage.js~tokenstorageserviceprovider",
    "class/src/providers/token-storage.js~TokenStorageServiceProvider.html",
    "<span>TokenStorageServiceProvider</span> <span class=\"search-result-import-path\">@meese-os/server/src/providers/token-storage.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/providers/vfs.js~vfsserviceprovider",
    "class/src/providers/vfs.js~VFSServiceProvider.html",
    "<span>VFSServiceProvider</span> <span class=\"search-result-import-path\">@meese-os/server/src/providers/vfs.js</span>",
    "class"
  ],
  [
    "@meese-os/server/src/utils/vfs.js~checkmountpointpermission",
    "function/index.html#static-function-checkMountpointPermission",
    "<span>checkMountpointPermission</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/vfs.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/utils/vfs.js~createerror",
    "function/index.html#static-function-createError",
    "<span>createError</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/vfs.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/utils/vfs.js~errorcodes",
    "variable/index.html#static-variable-errorCodes",
    "<span>errorCodes</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/vfs.js</span>",
    "variable"
  ],
  [
    "@meese-os/server/src/adapters/settings/fs.js~fs",
    "function/index.html#static-function-fs",
    "<span>fs</span> <span class=\"search-result-import-path\">@meese-os/server/src/adapters/settings/fs.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/utils/vfs.js~getprefix",
    "function/index.html#static-function-getPrefix",
    "<span>getPrefix</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/vfs.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/utils/vfs.js~methodarguments",
    "variable/index.html#static-variable-methodArguments",
    "<span>methodArguments</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/vfs.js</span>",
    "variable"
  ],
  [
    "@meese-os/server/src/utils/vfs.js~mountpointresolver",
    "function/index.html#static-function-mountpointResolver",
    "<span>mountpointResolver</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/vfs.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/adapters/auth/null.js~null",
    "function/index.html#static-function-null",
    "<span>null</span> <span class=\"search-result-import-path\">@meese-os/server/src/adapters/auth/null.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/adapters/settings/null.js~null",
    "function/index.html#static-function-null",
    "<span>null</span> <span class=\"search-result-import-path\">@meese-os/server/src/adapters/settings/null.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/utils/vfs.js~parsefields",
    "function/index.html#static-function-parseFields",
    "<span>parseFields</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/vfs.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/utils/vfs.js~sanitize",
    "function/index.html#static-function-sanitize",
    "<span>sanitize</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/vfs.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/utils/vfs.js~streamfromrequest",
    "function/index.html#static-function-streamFromRequest",
    "<span>streamFromRequest</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/vfs.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/adapters/vfs/system.js~system",
    "function/index.html#static-function-system",
    "<span>system</span> <span class=\"search-result-import-path\">@meese-os/server/src/adapters/vfs/system.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/utils/vfs.js~validategroups",
    "function/index.html#static-function-validateGroups",
    "<span>validateGroups</span> <span class=\"search-result-import-path\">@meese-os/server/src/utils/vfs.js</span>",
    "function"
  ],
  [
    "@meese-os/server/src/vfs.js~vfs",
    "function/index.html#static-function-vfs",
    "<span>vfs</span> <span class=\"search-result-import-path\">@meese-os/server/src/vfs.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/adapters/auth/null.js",
    "file/src/adapters/auth/null.js.html",
    "src/adapters/auth/null.js",
    "file"
  ],
  [
    "src/adapters/settings/fs.js",
    "file/src/adapters/settings/fs.js.html",
    "src/adapters/settings/fs.js",
    "file"
  ],
  [
    "src/adapters/settings/null.js",
    "file/src/adapters/settings/null.js.html",
    "src/adapters/settings/null.js",
    "file"
  ],
  [
    "src/adapters/vfs/system.js",
    "file/src/adapters/vfs/system.js.html",
    "src/adapters/vfs/system.js",
    "file"
  ],
  [
    "src/config.js",
    "file/src/config.js.html",
    "src/config.js",
    "file"
  ],
  [
    "src/core.js",
    "file/src/core.js.html",
    "src/core.js",
    "file"
  ],
  [
    "src/core.js~core#app",
    "class/src/core.js~Core.html#instance-member-app",
    "src/core.js~Core#app",
    "member"
  ],
  [
    "src/core.js~core#boot",
    "class/src/core.js~Core.html#instance-method-boot",
    "src/core.js~Core#boot",
    "method"
  ],
  [
    "src/core.js~core#broadcast",
    "class/src/core.js~Core.html#instance-method-broadcast",
    "src/core.js~Core#broadcast",
    "method"
  ],
  [
    "src/core.js~core#broadcastall",
    "class/src/core.js~Core.html#instance-method-broadcastAll",
    "src/core.js~Core#broadcastAll",
    "method"
  ],
  [
    "src/core.js~core#broadcastuser",
    "class/src/core.js~Core.html#instance-method-broadcastUser",
    "src/core.js~Core#broadcastUser",
    "method"
  ],
  [
    "src/core.js~core#constructor",
    "class/src/core.js~Core.html#instance-constructor-constructor",
    "src/core.js~Core#constructor",
    "method"
  ],
  [
    "src/core.js~core#destroy",
    "class/src/core.js~Core.html#instance-method-destroy",
    "src/core.js~Core#destroy",
    "method"
  ],
  [
    "src/core.js~core#httpserver",
    "class/src/core.js~Core.html#instance-member-httpServer",
    "src/core.js~Core#httpServer",
    "member"
  ],
  [
    "src/core.js~core#listen",
    "class/src/core.js~Core.html#instance-method-listen",
    "src/core.js~Core#listen",
    "method"
  ],
  [
    "src/core.js~core#session",
    "class/src/core.js~Core.html#instance-member-session",
    "src/core.js~Core#session",
    "member"
  ],
  [
    "src/core.js~core#start",
    "class/src/core.js~Core.html#instance-method-start",
    "src/core.js~Core#start",
    "method"
  ],
  [
    "src/core.js~core#ws",
    "class/src/core.js~Core.html#instance-member-ws",
    "src/core.js~Core#ws",
    "member"
  ],
  [
    "src/core.js~core#wss",
    "class/src/core.js~Core.html#instance-member-wss",
    "src/core.js~Core#wss",
    "member"
  ],
  [
    "src/core.js~core.getinstance",
    "class/src/core.js~Core.html#static-method-getInstance",
    "src/core.js~Core.getInstance",
    "method"
  ],
  [
    "src/filesystem.js",
    "file/src/filesystem.js.html",
    "src/filesystem.js",
    "file"
  ],
  [
    "src/filesystem.js~filesystem#_watch",
    "class/src/filesystem.js~Filesystem.html#instance-method-_watch",
    "src/filesystem.js~Filesystem#_watch",
    "method"
  ],
  [
    "src/filesystem.js~filesystem#adapters",
    "class/src/filesystem.js~Filesystem.html#instance-member-adapters",
    "src/filesystem.js~Filesystem#adapters",
    "member"
  ],
  [
    "src/filesystem.js~filesystem#call",
    "class/src/filesystem.js~Filesystem.html#instance-method-call",
    "src/filesystem.js~Filesystem#call",
    "method"
  ],
  [
    "src/filesystem.js~filesystem#constructor",
    "class/src/filesystem.js~Filesystem.html#instance-constructor-constructor",
    "src/filesystem.js~Filesystem#constructor",
    "method"
  ],
  [
    "src/filesystem.js~filesystem#core",
    "class/src/filesystem.js~Filesystem.html#instance-member-core",
    "src/filesystem.js~Filesystem#core",
    "member"
  ],
  [
    "src/filesystem.js~filesystem#destroy",
    "class/src/filesystem.js~Filesystem.html#instance-method-destroy",
    "src/filesystem.js~Filesystem#destroy",
    "method"
  ],
  [
    "src/filesystem.js~filesystem#init",
    "class/src/filesystem.js~Filesystem.html#instance-method-init",
    "src/filesystem.js~Filesystem#init",
    "method"
  ],
  [
    "src/filesystem.js~filesystem#mime",
    "class/src/filesystem.js~Filesystem.html#instance-method-mime",
    "src/filesystem.js~Filesystem#mime",
    "method"
  ],
  [
    "src/filesystem.js~filesystem#mount",
    "class/src/filesystem.js~Filesystem.html#instance-method-mount",
    "src/filesystem.js~Filesystem#mount",
    "method"
  ],
  [
    "src/filesystem.js~filesystem#mountpoints",
    "class/src/filesystem.js~Filesystem.html#instance-member-mountpoints",
    "src/filesystem.js~Filesystem#mountpoints",
    "member"
  ],
  [
    "src/filesystem.js~filesystem#options",
    "class/src/filesystem.js~Filesystem.html#instance-member-options",
    "src/filesystem.js~Filesystem#options",
    "member"
  ],
  [
    "src/filesystem.js~filesystem#realpath",
    "class/src/filesystem.js~Filesystem.html#instance-method-realpath",
    "src/filesystem.js~Filesystem#realpath",
    "method"
  ],
  [
    "src/filesystem.js~filesystem#request",
    "class/src/filesystem.js~Filesystem.html#instance-method-request",
    "src/filesystem.js~Filesystem#request",
    "method"
  ],
  [
    "src/filesystem.js~filesystem#unmount",
    "class/src/filesystem.js~Filesystem.html#instance-method-unmount",
    "src/filesystem.js~Filesystem#unmount",
    "method"
  ],
  [
    "src/filesystem.js~filesystem#watch",
    "class/src/filesystem.js~Filesystem.html#instance-method-watch",
    "src/filesystem.js~Filesystem#watch",
    "method"
  ],
  [
    "src/filesystem.js~filesystemadapter",
    "typedef/index.html#static-typedef-FilesystemAdapter",
    "src/filesystem.js~FilesystemAdapter",
    "typedef"
  ],
  [
    "src/filesystem.js~filesystemadaptermap",
    "typedef/index.html#static-typedef-FilesystemAdapterMap",
    "src/filesystem.js~FilesystemAdapterMap",
    "typedef"
  ],
  [
    "src/filesystem.js~filesystemcalloptions",
    "typedef/index.html#static-typedef-FilesystemCallOptions",
    "src/filesystem.js~FilesystemCallOptions",
    "typedef"
  ],
  [
    "src/filesystem.js~filesystemoptions",
    "typedef/index.html#static-typedef-FilesystemOptions",
    "src/filesystem.js~FilesystemOptions",
    "typedef"
  ],
  [
    "src/filesystem.js~mountpoint",
    "typedef/index.html#static-typedef-Mountpoint",
    "src/filesystem.js~Mountpoint",
    "typedef"
  ],
  [
    "src/package.js",
    "file/src/package.js.html",
    "src/package.js",
    "file"
  ],
  [
    "src/package.js~package#action",
    "class/src/package.js~Package.html#instance-method-action",
    "src/package.js~Package#action",
    "method"
  ],
  [
    "src/package.js~package#constructor",
    "class/src/package.js~Package.html#instance-constructor-constructor",
    "src/package.js~Package#constructor",
    "method"
  ],
  [
    "src/package.js~package#core",
    "class/src/package.js~Package.html#instance-member-core",
    "src/package.js~Package#core",
    "member"
  ],
  [
    "src/package.js~package#destroy",
    "class/src/package.js~Package.html#instance-method-destroy",
    "src/package.js~Package#destroy",
    "method"
  ],
  [
    "src/package.js~package#filename",
    "class/src/package.js~Package.html#instance-member-filename",
    "src/package.js~Package#filename",
    "member"
  ],
  [
    "src/package.js~package#init",
    "class/src/package.js~Package.html#instance-method-init",
    "src/package.js~Package#init",
    "method"
  ],
  [
    "src/package.js~package#metadata",
    "class/src/package.js~Package.html#instance-member-metadata",
    "src/package.js~Package#metadata",
    "member"
  ],
  [
    "src/package.js~package#resource",
    "class/src/package.js~Package.html#instance-method-resource",
    "src/package.js~Package#resource",
    "method"
  ],
  [
    "src/package.js~package#start",
    "class/src/package.js~Package.html#instance-method-start",
    "src/package.js~Package#start",
    "method"
  ],
  [
    "src/package.js~package#validate",
    "class/src/package.js~Package.html#instance-method-validate",
    "src/package.js~Package#validate",
    "method"
  ],
  [
    "src/package.js~package#watch",
    "class/src/package.js~Package.html#instance-method-watch",
    "src/package.js~Package#watch",
    "method"
  ],
  [
    "src/package.js~packagemetadata",
    "typedef/index.html#static-typedef-PackageMetadata",
    "src/package.js~PackageMetadata",
    "typedef"
  ],
  [
    "src/package.js~packageoptions",
    "typedef/index.html#static-typedef-PackageOptions",
    "src/package.js~PackageOptions",
    "typedef"
  ],
  [
    "src/packages.js",
    "file/src/packages.js.html",
    "src/packages.js",
    "file"
  ],
  [
    "src/packages.js~packages#constructor",
    "class/src/packages.js~Packages.html#instance-constructor-constructor",
    "src/packages.js~Packages#constructor",
    "method"
  ],
  [
    "src/packages.js~packages#core",
    "class/src/packages.js~Packages.html#instance-member-core",
    "src/packages.js~Packages#core",
    "member"
  ],
  [
    "src/packages.js~packages#createloader",
    "class/src/packages.js~Packages.html#instance-method-createLoader",
    "src/packages.js~Packages#createLoader",
    "method"
  ],
  [
    "src/packages.js~packages#destroy",
    "class/src/packages.js~Packages.html#instance-method-destroy",
    "src/packages.js~Packages#destroy",
    "method"
  ],
  [
    "src/packages.js~packages#handlemessage",
    "class/src/packages.js~Packages.html#instance-method-handleMessage",
    "src/packages.js~Packages#handleMessage",
    "method"
  ],
  [
    "src/packages.js~packages#init",
    "class/src/packages.js~Packages.html#instance-method-init",
    "src/packages.js~Packages#init",
    "method"
  ],
  [
    "src/packages.js~packages#initializepackage",
    "class/src/packages.js~Packages.html#instance-method-initializePackage",
    "src/packages.js~Packages#initializePackage",
    "method"
  ],
  [
    "src/packages.js~packages#load",
    "class/src/packages.js~Packages.html#instance-method-load",
    "src/packages.js~Packages#load",
    "method"
  ],
  [
    "src/packages.js~packages#loadpackage",
    "class/src/packages.js~Packages.html#instance-method-loadPackage",
    "src/packages.js~Packages#loadPackage",
    "method"
  ],
  [
    "src/packages.js~packages#onpackagechanged",
    "class/src/packages.js~Packages.html#instance-method-onPackageChanged",
    "src/packages.js~Packages#onPackageChanged",
    "method"
  ],
  [
    "src/packages.js~packages#options",
    "class/src/packages.js~Packages.html#instance-member-options",
    "src/packages.js~Packages#options",
    "member"
  ],
  [
    "src/packages.js~packages#packages",
    "class/src/packages.js~Packages.html#instance-member-packages",
    "src/packages.js~Packages#packages",
    "member"
  ],
  [
    "src/packages.js~packages#start",
    "class/src/packages.js~Packages.html#instance-method-start",
    "src/packages.js~Packages#start",
    "method"
  ],
  [
    "src/packages.js~packagesoptions",
    "typedef/index.html#static-typedef-PackagesOptions",
    "src/packages.js~PackagesOptions",
    "typedef"
  ],
  [
    "src/providers/auth.js",
    "file/src/providers/auth.js.html",
    "src/providers/auth.js",
    "file"
  ],
  [
    "src/providers/auth.js~authserviceprovider#depends",
    "class/src/providers/auth.js~AuthServiceProvider.html#instance-method-depends",
    "src/providers/auth.js~AuthServiceProvider#depends",
    "method"
  ],
  [
    "src/providers/core.js",
    "file/src/providers/core.js.html",
    "src/providers/core.js",
    "file"
  ],
  [
    "src/providers/core.js~coreserviceprovider#constructor",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-constructor-constructor",
    "src/providers/core.js~CoreServiceProvider#constructor",
    "method"
  ],
  [
    "src/providers/core.js~coreserviceprovider#destroy",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-method-destroy",
    "src/providers/core.js~CoreServiceProvider#destroy",
    "method"
  ],
  [
    "src/providers/core.js~coreserviceprovider#init",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-method-init",
    "src/providers/core.js~CoreServiceProvider#init",
    "method"
  ],
  [
    "src/providers/core.js~coreserviceprovider#initdevelopertools",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-method-initDeveloperTools",
    "src/providers/core.js~CoreServiceProvider#initDeveloperTools",
    "method"
  ],
  [
    "src/providers/core.js~coreserviceprovider#initextensions",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-method-initExtensions",
    "src/providers/core.js~CoreServiceProvider#initExtensions",
    "method"
  ],
  [
    "src/providers/core.js~coreserviceprovider#initproxies",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-method-initProxies",
    "src/providers/core.js~CoreServiceProvider#initProxies",
    "method"
  ],
  [
    "src/providers/core.js~coreserviceprovider#initresourceroutes",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-method-initResourceRoutes",
    "src/providers/core.js~CoreServiceProvider#initResourceRoutes",
    "method"
  ],
  [
    "src/providers/core.js~coreserviceprovider#initservice",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-method-initService",
    "src/providers/core.js~CoreServiceProvider#initService",
    "method"
  ],
  [
    "src/providers/core.js~coreserviceprovider#initsocketroutes",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-method-initSocketRoutes",
    "src/providers/core.js~CoreServiceProvider#initSocketRoutes",
    "method"
  ],
  [
    "src/providers/core.js~coreserviceprovider#start",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-method-start",
    "src/providers/core.js~CoreServiceProvider#start",
    "method"
  ],
  [
    "src/providers/core.js~coreserviceprovider#watches",
    "class/src/providers/core.js~CoreServiceProvider.html#instance-member-watches",
    "src/providers/core.js~CoreServiceProvider#watches",
    "member"
  ],
  [
    "src/providers/core.js~coreserviceprovider.provides",
    "class/src/providers/core.js~CoreServiceProvider.html#static-method-provides",
    "src/providers/core.js~CoreServiceProvider.provides",
    "method"
  ],
  [
    "src/providers/packages.js",
    "file/src/providers/packages.js.html",
    "src/providers/packages.js",
    "file"
  ],
  [
    "src/providers/packages.js~packageserviceprovider#constructor",
    "class/src/providers/packages.js~PackageServiceProvider.html#instance-constructor-constructor",
    "src/providers/packages.js~PackageServiceProvider#constructor",
    "method"
  ],
  [
    "src/providers/packages.js~packageserviceprovider#initdevelopertools",
    "class/src/providers/packages.js~PackageServiceProvider.html#instance-method-initDeveloperTools",
    "src/providers/packages.js~PackageServiceProvider#initDeveloperTools",
    "method"
  ],
  [
    "src/providers/settings.js",
    "file/src/providers/settings.js.html",
    "src/providers/settings.js",
    "file"
  ],
  [
    "src/providers/settings.js~settingsserviceprovider#constructor",
    "class/src/providers/settings.js~SettingsServiceProvider.html#instance-constructor-constructor",
    "src/providers/settings.js~SettingsServiceProvider#constructor",
    "method"
  ],
  [
    "src/providers/token-factory.js",
    "file/src/providers/token-factory.js.html",
    "src/providers/token-factory.js",
    "file"
  ],
  [
    "src/providers/token-factory.js~tokenfactoryserviceprovider#constructor",
    "class/src/providers/token-factory.js~TokenFactoryServiceProvider.html#instance-constructor-constructor",
    "src/providers/token-factory.js~TokenFactoryServiceProvider#constructor",
    "method"
  ],
  [
    "src/providers/token-factory.js~tokenfactoryserviceprovider#core",
    "class/src/providers/token-factory.js~TokenFactoryServiceProvider.html#instance-member-core",
    "src/providers/token-factory.js~TokenFactoryServiceProvider#core",
    "member"
  ],
  [
    "src/providers/token-factory.js~tokenfactoryserviceprovider#depends",
    "class/src/providers/token-factory.js~TokenFactoryServiceProvider.html#instance-method-depends",
    "src/providers/token-factory.js~TokenFactoryServiceProvider#depends",
    "method"
  ],
  [
    "src/providers/token-factory.js~tokenfactoryserviceprovider#destroy",
    "class/src/providers/token-factory.js~TokenFactoryServiceProvider.html#instance-method-destroy",
    "src/providers/token-factory.js~TokenFactoryServiceProvider#destroy",
    "method"
  ],
  [
    "src/providers/token-factory.js~tokenfactoryserviceprovider#init",
    "class/src/providers/token-factory.js~TokenFactoryServiceProvider.html#instance-method-init",
    "src/providers/token-factory.js~TokenFactoryServiceProvider#init",
    "method"
  ],
  [
    "src/providers/token-factory.js~tokenfactoryserviceprovider#provides",
    "class/src/providers/token-factory.js~TokenFactoryServiceProvider.html#instance-method-provides",
    "src/providers/token-factory.js~TokenFactoryServiceProvider#provides",
    "method"
  ],
  [
    "src/providers/token-factory.js~tokenfactoryserviceprovider#tokenfactory",
    "class/src/providers/token-factory.js~TokenFactoryServiceProvider.html#instance-member-tokenFactory",
    "src/providers/token-factory.js~TokenFactoryServiceProvider#tokenFactory",
    "member"
  ],
  [
    "src/providers/token-storage.js",
    "file/src/providers/token-storage.js.html",
    "src/providers/token-storage.js",
    "file"
  ],
  [
    "src/providers/token-storage.js~tokenstorageserviceprovider#constructor",
    "class/src/providers/token-storage.js~TokenStorageServiceProvider.html#instance-constructor-constructor",
    "src/providers/token-storage.js~TokenStorageServiceProvider#constructor",
    "method"
  ],
  [
    "src/providers/token-storage.js~tokenstorageserviceprovider#core",
    "class/src/providers/token-storage.js~TokenStorageServiceProvider.html#instance-member-core",
    "src/providers/token-storage.js~TokenStorageServiceProvider#core",
    "member"
  ],
  [
    "src/providers/token-storage.js~tokenstorageserviceprovider#destroy",
    "class/src/providers/token-storage.js~TokenStorageServiceProvider.html#instance-method-destroy",
    "src/providers/token-storage.js~TokenStorageServiceProvider#destroy",
    "method"
  ],
  [
    "src/providers/token-storage.js~tokenstorageserviceprovider#init",
    "class/src/providers/token-storage.js~TokenStorageServiceProvider.html#instance-method-init",
    "src/providers/token-storage.js~TokenStorageServiceProvider#init",
    "method"
  ],
  [
    "src/providers/token-storage.js~tokenstorageserviceprovider#provides",
    "class/src/providers/token-storage.js~TokenStorageServiceProvider.html#instance-method-provides",
    "src/providers/token-storage.js~TokenStorageServiceProvider#provides",
    "method"
  ],
  [
    "src/providers/token-storage.js~tokenstorageserviceprovider#storage",
    "class/src/providers/token-storage.js~TokenStorageServiceProvider.html#instance-member-storage",
    "src/providers/token-storage.js~TokenStorageServiceProvider#storage",
    "member"
  ],
  [
    "src/providers/vfs.js",
    "file/src/providers/vfs.js.html",
    "src/providers/vfs.js",
    "file"
  ],
  [
    "src/providers/vfs.js~vfsserviceprovider#constructor",
    "class/src/providers/vfs.js~VFSServiceProvider.html#instance-constructor-constructor",
    "src/providers/vfs.js~VFSServiceProvider#constructor",
    "method"
  ],
  [
    "src/settings.js",
    "file/src/settings.js.html",
    "src/settings.js",
    "file"
  ],
  [
    "src/settings.js~settings#constructor",
    "class/src/settings.js~Settings.html#instance-constructor-constructor",
    "src/settings.js~Settings#constructor",
    "method"
  ],
  [
    "src/settings.js~settings#core",
    "class/src/settings.js~Settings.html#instance-member-core",
    "src/settings.js~Settings#core",
    "member"
  ],
  [
    "src/settings.js~settings#destroy",
    "class/src/settings.js~Settings.html#instance-method-destroy",
    "src/settings.js~Settings#destroy",
    "method"
  ],
  [
    "src/settings.js~settings#init",
    "class/src/settings.js~Settings.html#instance-method-init",
    "src/settings.js~Settings#init",
    "method"
  ],
  [
    "src/settings.js~settings#load",
    "class/src/settings.js~Settings.html#instance-method-load",
    "src/settings.js~Settings#load",
    "method"
  ],
  [
    "src/settings.js~settings#save",
    "class/src/settings.js~Settings.html#instance-method-save",
    "src/settings.js~Settings#save",
    "method"
  ],
  [
    "src/settings.js~settingsadapter",
    "typedef/index.html#static-typedef-SettingsAdapter",
    "src/settings.js~SettingsAdapter",
    "typedef"
  ],
  [
    "src/settings.js~settingsoptions",
    "typedef/index.html#static-typedef-SettingsOptions",
    "src/settings.js~SettingsOptions",
    "typedef"
  ],
  [
    "src/utils/token-factory.js",
    "file/src/utils/token-factory.js.html",
    "src/utils/token-factory.js",
    "file"
  ],
  [
    "src/utils/token-factory.js~tokenfactory#constructor",
    "class/src/utils/token-factory.js~TokenFactory.html#instance-constructor-constructor",
    "src/utils/token-factory.js~TokenFactory#constructor",
    "method"
  ],
  [
    "src/utils/token-factory.js~tokenfactory#core",
    "class/src/utils/token-factory.js~TokenFactory.html#instance-member-core",
    "src/utils/token-factory.js~TokenFactory#core",
    "member"
  ],
  [
    "src/utils/token-factory.js~tokenfactory#createaccesstoken",
    "class/src/utils/token-factory.js~TokenFactory.html#instance-method-createAccessToken",
    "src/utils/token-factory.js~TokenFactory#createAccessToken",
    "method"
  ],
  [
    "src/utils/token-factory.js~tokenfactory#createrefreshtoken",
    "class/src/utils/token-factory.js~TokenFactory.html#instance-method-createRefreshToken",
    "src/utils/token-factory.js~TokenFactory#createRefreshToken",
    "method"
  ],
  [
    "src/utils/token-factory.js~tokenfactory#init",
    "class/src/utils/token-factory.js~TokenFactory.html#instance-method-init",
    "src/utils/token-factory.js~TokenFactory#init",
    "method"
  ],
  [
    "src/utils/token-factory.js~tokenfactory#options",
    "class/src/utils/token-factory.js~TokenFactory.html#instance-member-options",
    "src/utils/token-factory.js~TokenFactory#options",
    "member"
  ],
  [
    "src/utils/token-factory.js~tokenfactory#refreshtoaccesstoken",
    "class/src/utils/token-factory.js~TokenFactory.html#instance-method-refreshToAccessToken",
    "src/utils/token-factory.js~TokenFactory#refreshToAccessToken",
    "method"
  ],
  [
    "src/utils/token-factory.js~tokenfactory#storage",
    "class/src/utils/token-factory.js~TokenFactory.html#instance-member-storage",
    "src/utils/token-factory.js~TokenFactory#storage",
    "member"
  ],
  [
    "src/utils/token-factory.js~tokenfactory#validateaccesstoken",
    "class/src/utils/token-factory.js~TokenFactory.html#instance-method-validateAccessToken",
    "src/utils/token-factory.js~TokenFactory#validateAccessToken",
    "method"
  ],
  [
    "src/utils/token-factory.js~tokenfactory#validaterefreshtoken",
    "class/src/utils/token-factory.js~TokenFactory.html#instance-method-validateRefreshToken",
    "src/utils/token-factory.js~TokenFactory#validateRefreshToken",
    "method"
  ],
  [
    "src/utils/token-factory.js~tokenfactoryoptions",
    "typedef/index.html#static-typedef-TokenFactoryOptions",
    "src/utils/token-factory.js~TokenFactoryOptions",
    "typedef"
  ],
  [
    "src/utils/token-storage.js",
    "file/src/utils/token-storage.js.html",
    "src/utils/token-storage.js",
    "file"
  ],
  [
    "src/utils/token-storage.js~tokenstorage#constructor",
    "class/src/utils/token-storage.js~TokenStorage.html#instance-constructor-constructor",
    "src/utils/token-storage.js~TokenStorage#constructor",
    "method"
  ],
  [
    "src/utils/token-storage.js~tokenstorage#core",
    "class/src/utils/token-storage.js~TokenStorage.html#instance-member-core",
    "src/utils/token-storage.js~TokenStorage#core",
    "member"
  ],
  [
    "src/utils/token-storage.js~tokenstorage#create",
    "class/src/utils/token-storage.js~TokenStorage.html#instance-method-create",
    "src/utils/token-storage.js~TokenStorage#create",
    "method"
  ],
  [
    "src/utils/token-storage.js~tokenstorage#destroy",
    "class/src/utils/token-storage.js~TokenStorage.html#instance-method-destroy",
    "src/utils/token-storage.js~TokenStorage#destroy",
    "method"
  ],
  [
    "src/utils/token-storage.js~tokenstorage#find",
    "class/src/utils/token-storage.js~TokenStorage.html#instance-method-find",
    "src/utils/token-storage.js~TokenStorage#find",
    "method"
  ],
  [
    "src/utils/token-storage.js~tokenstorage#init",
    "class/src/utils/token-storage.js~TokenStorage.html#instance-method-init",
    "src/utils/token-storage.js~TokenStorage#init",
    "method"
  ],
  [
    "src/utils/token-storage.js~tokenstorage#options",
    "class/src/utils/token-storage.js~TokenStorage.html#instance-member-options",
    "src/utils/token-storage.js~TokenStorage#options",
    "member"
  ],
  [
    "src/utils/token-storage.js~tokenstorage#remove",
    "class/src/utils/token-storage.js~TokenStorage.html#instance-method-remove",
    "src/utils/token-storage.js~TokenStorage#remove",
    "method"
  ],
  [
    "src/utils/token-storage.js~tokenstorageoptions",
    "typedef/index.html#static-typedef-TokenStorageOptions",
    "src/utils/token-storage.js~TokenStorageOptions",
    "typedef"
  ],
  [
    "src/utils/vfs.js",
    "file/src/utils/vfs.js.html",
    "src/utils/vfs.js",
    "file"
  ],
  [
    "src/vfs.js",
    "file/src/vfs.js.html",
    "src/vfs.js",
    "file"
  ]
]